### ISSUE TITLE
Dataset split code is needed.

### ISSUE THREAD

**Issue by liuqidong07** [tsinghua-fib-lab/DICE#1]
Hello, I read your paper and find it a fantastic work. 
But I have some trouble in dataset split. Could you please share your dataset split code with me if it is convenient?
Thanks a lot!

Qidong Liu

**Comment by ruanqin0706** [comment]
Similar question here, can you also release code snippets for constructing data? 

Thanks in advance.

**Comment by knowledge-graph21** [comment]
I have the same question, can you disclose your data pre-processing code?
Thanks a lot！

**Comment by DavyMorgan** [comment]
> Hello, I read your paper and find it a fantastic work.
> But I have some trouble in dataset split. Could you please share your dataset split code with me if it is convenient?
> Thanks a lot!
> 
> Qidong Liu



> Similar question here, can you also release code snippets for constructing data?
> 
> Thanks in advance.



> I have the same question, can you disclose your data pre-processing code?
> Thanks a lot！

Hi, all. Thank you for your attention on our work. The data pre-processing codes are in another repo [here](https://github.com/DavyMorgan/dps). You can use those codes to generate training/validation/test data for DICE. Particularly, the core logic on obtaining biased and unbiased data by sampling can be find at this function [here](https://github.com/DavyMorgan/dps/blob/19a3e5fb2cb6932c3f093ed443760ecd3d95bfdb/data_process_service/utils.py#L211).

**Comment by liuqidong07** [comment]
Thanks for your relpy! I'll read the code.
