### ISSUE TITLE
关于数据集处理的细节询问

### ISSUE THREAD

**Issue by cizhouyu** [tsinghua-fib-lab/DICE#10]
作者您好！感谢您贡献的高质量论文和代码。
关于数据集处理，我理解是这样做的：首先按照物品流行度的倒数采样出40%作为intervened数据（intervened数据随机地分为四份），另外60%作为normal数据；normal数据和一份intervened数据合在一起作为training set；一份intervened数据作为validation set；两份intervened数据作为test set。
请问您是这样做的吗？如果我理解有偏差，希望您指正，谢谢！
![image](https://github.com/tsinghua-fib-lab/DICE/assets/60316519/02e05fc3-b5c2-4afc-9b1e-4e0f9e972e1d)
![image](https://github.com/tsinghua-fib-lab/DICE/assets/60316519/f4cbcf5f-6717-403d-aea4-2e374e944928)

**Comment by DavyMorgan** [comment]
嗯嗯 是的，您理解的没有问题

**Comment by cizhouyu** [comment]
好的，谢谢！
