### ISSUE TITLE
请教下DICE在IID的测试集上的表现

### ISSUE THREAD

**Issue by kyriemao** [tsinghua-fib-lab/DICE#2]
作者您好，

您的工作让我很受启发，有一个问题想请教一下您: 

> 为什么解耦了interest和conformity向量后，模型就会在所有item popularity都一样的测试集上效果好呢？

如果DICE在IID的测试集上表现好这个我可以理解，因为解耦出这两个向量后能更细粒度地建模interaction。但我理解的是，DICE最后还是concate两个embedding来做预测的，所以不太明白是什么因素导致它在non-IID的测试集上性能好。

非常感谢！

**Comment by DavyMorgan** [comment]
这是一个很好的问题！我们这里的non-IID测试集表示不同popularity的item有几乎相等的概率出现在推荐列表中，而不是所有item的popularity一样。可以这样理解：用户能够看到一个推荐列表，列表当中每个推荐的item会显示它的内容和它的销量，在IID测试集中，列表里大部分item的销量都很高，而在non-IID测试集中，列表里高销量和低销量的item的数量基本一致。而无论是IID还是non-IID，用户都会看到item的销量数字，因此都会受到从众心理的影响，所以在DICE里是concate两个embedding来做预测的。只不过两种情况下用户从众心理的影响强度是不同的，所以将兴趣和从众解纠缠能够解决用户从众心理变化的场景。您的建议也很好，我们的实验都是在non-IID测试集上评估的，包括对比了concat两个embedding和只使用一个embedding。在IID的测试集上也评估一下性能应该能够有一些更有意思的结论，不过解纠缠的优势可能还是在某个因素发生变化的non-IID情况下能最大的发挥出来。

**Comment by kyriemao** [comment]
明白了，非常感谢您的回答！
