### ISSUE TITLE
进行test_iou时缺少reccommender的PopularityRecommender子类

### ISSUE THREAD

**Issue by WunaiDczh** [tsinghua-fib-lab/DICE#3]
您好，感谢您开源研究代码，但是我在进行iou测试时，发现reccommender中缺少PopularityRecommender子类，不知道是哪里的问题，期待您的回复，O(∩_∩)O谢谢

**Comment by DavyMorgan** [comment]
您好，感谢指出，已在这个commit[[link](https://github.com/tsinghua-fib-lab/DICE/commit/03bc56e6322eb2d1f3383c5eb7173e4003612d4b)]中增加了PopularityRecommender
