### ISSUE TITLE
打分融合

### ISSUE THREAD

**Issue by daidaren202** [tsinghua-fib-lab/DICE#4]
作者您好，非常直观有趣的工作。
请问有考虑过用MLP融合代替兴趣和从众拼接融合吗？这种做法相较于拼接有哪些优劣呢？期待您的回复。

**Comment by DavyMorgan** [comment]
这是一个很好的问题。可以参考之前的这个[issue](https://github.com/tsinghua-fib-lab/DICE/issues/2#issuecomment-953484413)。我们采用拼接是一种比较简洁的融合方式，最终实验的性能也是不错的。在不同的交互行为中，兴趣与从众两方面的权重可能存在变化，用MLP的灵活性会更好，有建模这种权重变化的潜力，不过每一次具体交互中兴趣与从众的权重是没有真值的，因此用MLP也是无监督的方式建模兴趣和从众的权重，实际效果还是需要通过实验来验证。

**Comment by daidaren202** [comment]
感谢您的回答。我在自己数据集上的结果，融合后的hitrate和只使用流行度分支的hitrate差距还蛮大的，请问有单独使用两个分支的embedding的hitrate结果吗？

**Comment by DavyMorgan** [comment]
我们没有测试单独embedding的hitrate。只使用流行度分支在IID评估中效果可能是不错的，我们的paper里更加关注non-IID场景下的评估。
