### ISSUE TITLE
popularity

### ISSUE THREAD

**Issue by jhliu0807** [tsinghua-fib-lab/DICE#5]
作者您好！
（1）请问与popularity相关的文件（popularity_all.npy, popularity_skew.npy, popularity_blend.npy, popularity.npy）的含义是什么？是统计了item的交互次数吗？它们的区别是什么？
（2）如果我没理解错，您在复现IPS时，是用item出现次数的倒数对样本进行加权，对吗？
最近需要复现一下用IPS对流行度进行消偏，向您请教一下具体的实现细节。

**Comment by DavyMorgan** [comment]
您好！感谢您关注我们的工作。
（1）popularity文件统计了item的交互次数。popularity_all.npy是完整数据集的统计结果，由于CausE模型的训练集包括有偏数据和无偏数据，所以分别做了统计，popularity_skew.npy是无偏数据的统计结果，popularity.npy是有偏数据的统计结果，popularity_blend.npy是训练集（无偏+有偏）的统计结果。
（2）是的，用item出现次数的倒数对样本进行加权

**Comment by jhliu0807** [comment]
感谢
