### ISSUE TITLE
Issues related to dataset processing

### ISSUE THREAD

**Issue by GXNU156489** [tsinghua-fib-lab/DICE#8]
Hello author. In the ml10m dataset, they are officially described as having 71,567 users, while the paper counts only 37,962 users, I would like to ask why this is so and how did you handle the dataset.
![image](https://github.com/tsinghua-fib-lab/DICE/assets/36919834/9c863726-dae8-4f93-9df2-0ee88a7df44e)
![image](https://github.com/tsinghua-fib-lab/DICE/assets/36919834/6445010c-db39-4ea4-a9b2-2c64f8085962)

**Comment by DavyMorgan** [comment]
Thanks for your question. We adopt 10-core filtering to pre-process the dataset and also down-sample the users, thus the experimental dataset is smaller than the original one.
