### ISSUE TITLE
Experimental details

### ISSUE THREAD

**Issue by pwn1024** [tsinghua-fib-lab/DICE#9]
hi~

Thank you for your great work and code contribution！

I am also working in this area.I would like to inquire about some experimental details. Especially the detailed explanation of the Visualization of the learned item embeddings in DICE experiment.

Can you share the code？I will refer to your work in future work.

Looking forward to your reply, thank you！

![image](https://github.com/tsinghua-fib-lab/DICE/assets/148890724/c873a958-4a2a-423a-88dc-b33210064864)

**Comment by DavyMorgan** [comment]
I have uploaded the visualization codes. Please check this [commit](https://github.com/tsinghua-fib-lab/DICE/commit/1aecbe8cb3b144c8b00433ec77fa81eef901cbf2).
